### ISSUE TITLE
Is it possible to use vue-record with NuxtJS?

### ISSUE THREAD

**Issue by ChristianFenn** [codekraft-studio/vue-record#18]
Hello, I'd love to use this in a NuxtJS application I'm building.

Currently when importing the component I'm seeing this in the terminal:

<img width="393" alt="Screen Shot 2020-07-22 at 5 32 55 PM" src="https://user-images.githubusercontent.com/53135800/88242235-74a2fa80-cc41-11ea-8341-a7b98deee3da.png">

I think this is basically saying Tone.js isn't supported in the browser, which is actually not even a browser, it's first rendering on the server side.

I'm importing it into my component as follows:

```
  import VueRecord from '@codekraft-studio/vue-record'

  export default {
    mixins: [authenticated],
    components: {
      // other components
      VueRecord,
    },
...
```

and the component used in the HTML section is like:
```
<client-only> <!-- client-only doesn't help here -->
    <VueRecordAudio @result="onResult" />
</client-only>
```

In the browser I get a 500 saying "document is not defined". Any ideas what I might be missing to use this in a NuxtJS application, or is the library not supported outside of vue-only applications?

**Comment by hamidm21** [comment]
i have the same problem

**Comment by hamidm21** [comment]
hi @NitroStoutPlz,
i think i found the solution to this problem, this happens because the document object is not accessible for the package to work if you're using SSR within your nuxt app.

and to work around this you need to add .client.js at the end of your plugin file, according to this [answer](https://stackoverflow.com/a/58633076) in stack overflow.

it worked for me, i hope it solves your problem too.

**Comment by ChristianFenn** [comment]
@hamidm21 Awesome! Thank you very much for letting me know about this 👍

**Comment by hamidm21** [comment]
happy i could help. 🙏
